---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  roles:
  - role: hth.sublime
    vars:
      sublime:
        configs:
          - user: bob
            preferences:
              path: preferences
            keymap:
              path: keymap
