- name: "HTH | Sublime | Assertion | Run assertions"
  ansible.utils.validate:
    data: "{{ sublime }}"
    criteria: "{{ lookup('file', 'assertions/criteria/sublime-criteria.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost
  when:
    - sublime is defined

- name: "HTH | Sublime | Configure repository"
  ansible.builtin.include_tasks: repository.yml
  when:
    - sublime is defined

- name: "HTH | Sublime | Manage installation"
  ansible.builtin.apt:
    name: "{{ 'sublime-text' if(sublime.remove is defined and sublime.remove or sublime.version is undefined) else 'sublime-text=' + (sublime.version | string)  }}"
    state: "{{ 'absent' if (sublime.remove is defined and sublime.remove) else 'latest' if (sublime.version is undefined) else 'present' }}"
    update_cache: yes
    allow_downgrade: yes
  when:
    - sublime is defined
