---
- name: Verify
  hosts: all
  vars_files:
    - "../../defaults/main.yml"
  tasks:

  - name: Look up sublime package version
    command: subl --version
    register: sublime_version
    changed_when: false
    failed_when: false

  - name: Ensure sublime package was removed
    fail:
      msg: "'subl' is still installed"
    when: not sublime_version.rc != 0

  - name: Lookup for repository signing key
    stat:
      path: "{{ hth_sublime_repository_signing_key_path }}"
    register: sublime_repo_signing_key_stat

  - name: Ensure repository signing key was removed
    fail:
      msg: "Repository signing key for Sublime was still found!"
    when: sublime_repo_signing_key_stat.stat.exists

  - name: Lookup for priority file
    stat:
      path: "{{ hth_sublime_apt_preference_path }}"
    register: sublime_prefs_stat

  - name: Ensure priority file was removed
    fail:
      msg: "apt preference file for Sublime was still found!"
    when: sublime_prefs_stat.stat.exists

  - name: Check if apt repository is still configured
    ansible.builtin.command:
      cmd: grep -r "{{ hth_sublime_apt_repository_url }}" /etc/apt/sources.list /etc/apt/sources.list.d/
    register: sublime_apt_repo
    changed_when: false
    failed_when: false

  - name: Ensure apt repository was removed
    fail:
      msg: "Sublime apt repository is still present!"
    when:
      - sublime_apt_repo.rc == 0
