name: quality-gate

on:
  # allow manual triggering of action
  workflow_dispatch:

  # Allow other workflows to invoke this workflow
  workflow_call:

  pull_request:
    branches:
      - "main"

  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Molecule
      run: |
        pip install -U pip setuptools wheel
        pip install ansible ansible-lint molecule molecule-plugins[docker]

    - name: Test latest install
      run: molecule  test --scenario-name install-latest

    - name: Test specific version install
      run: molecule test --scenario-name install-version

    - name: Test config
      run: molecule test --scenario-name configs

    - name: Test removal
      run: molecule test --scenario-name remove
